
s3_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['S3_SECRET_KEY'] %>
s3_bucket: <%= ENV['S3_STAGING_BUCKET'] %>
s3_endpoint: <%= ENV['S3_STAGING_REGION'] %>
exclude_from_upload:
 - config
 - .travis.yml
 - .gitignore
